version: 2.1
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:8.3
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: npm test
  deploy:
    docker:
      - image: circleci/node:8.3
    steps:
      - checkout
      - run:
          name: Deploy to Heroku
          command: |
          git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master

workflows:
  version: 2.1
  build_deploy:
    jobs:
      - build
      - deploy:
          requires:
            -build
          filters:
            branches:
              only: master
