version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:8.3
    working_directory: ~/repo
    steps:
      - checkout
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: npm test
      - run:
          name: Deploy to Heroku
          command: git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master
